<?php

return [
    'multi_language' => true,
    'localizationManager' => \Step2dev\LazyAdmin\Localization\LocalizationManager::class,
    'supported_locales' => [
        'en',
    ],
    /* -----------------------------------------------------------------
     |  Locales
     | -----------------------------------------------------------------
     */

    'locales' => [
        // A
        //====================================================>
        'aa' => [
            'name' => 'Afar',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Qafar',
            'regional' => 'aa_ER',
            'flag' => '🇪🇷',
        ],
        'ab' => [
            'name' => 'Abkhazian',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Аҧсуа',
            'regional' => '',
            'flag' => '🇬🇪',
        ],
        'ace' => [
            'name' => 'Achinese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Aceh',
            'regional' => '',
            'flag' => '🇮🇩',
        ],
        'ady' => [
            'name' => 'Adyghe',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Адыгэбзэ',
            'regional' => '',
            'flag' => '🇷🇺',
        ],
        'ae' => [
            'name' => 'Avestan',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Avesta',
            'regional' => '',
            'flag' => '🇮🇷',
        ],
        'af' => [
            'name' => 'Afrikaans',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Afrikaans',
            'regional' => 'af_ZA',
            'flag' => '🇿🇦',
        ],
        'agq' => [
            'name' => 'Aghem',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Aghem',
            'regional' => '',
            'flag' => '🇨🇲',
        ],
        'ak' => [
            'name' => 'Akan',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Akan',
            'regional' => 'ak_GH',
            'flag' => '🇬🇭',
        ],
        'ale' => [
            'name' => 'Aleut',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Unangax tunuu',
            'regional' => '',
            'flag' => '🇺🇸',
        ],
        'am' => [
            'name' => 'Amharic',
            'script' => 'Ethi',
            'dir' => 'ltr',
            'native' => 'አማርኛ',
            'regional' => 'am_ET',
            'flag' => '🇪🇹',
        ],
        'an' => [
            'name' => 'Aragonese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Aragonés',
            'regional' => 'an_ES',
            'flag' => '🇪🇸',
        ],
        'ang' => [
            'name' => 'Old English',
            'script' => 'Runr',
            'dir' => 'ltr',
            'native' => 'Old English',
            'regional' => '',
            'flag' => '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
        ],
        'ar' => [
            'name' => 'Arabic',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'العربية',
            'regional' => 'ar_AE',
            'flag' => '🇦🇪',
        ],
        'as' => [
            'name' => 'Assamese',
            'script' => 'Beng',
            'dir' => 'ltr',
            'native' => 'অসমীয়া',
            'regional' => 'as_IN',
            'flag' => '🇮🇳',
        ],
        'asa' => [
            'name' => 'Kipare',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kipare',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'av' => [
            'name' => 'Avaric',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Авар мацӀ',
            'regional' => '',
            'flag' => '🇷🇺',
        ],
        'ay' => [
            'name' => 'Aymara',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Aymar aru',
            'regional' => 'ay_PE',
            'flag' => '🇵🇪',
        ],
        'az' => [
            'name' => 'Azerbaijani (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Azərbaycanca',
            'regional' => 'az_AZ',
            'flag' => '🇦🇿',
        ],
        'az-Cyrl' => [
            'name' => 'Azerbaijani (Cyrillic)',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Азәрбајҹан',
            'regional' => 'uz_UZ',
            'flag' => '🇦🇿',
        ],

        // B
        //====================================================>
        'ba' => [
            'name' => 'Bashkir',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Башҡорт теле',
            'regional' => '',
            'flag' => '🇷🇺',
        ],
        'bas' => [
            'name' => 'Basa',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ɓàsàa',
            'regional' => '',
            'flag' => '🇨🇲',
        ],
        'be' => [
            'name' => 'Belarusian',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Беларуская',
            'regional' => 'be_BY',
            'flag' => '🇧🇾',
        ],
        'bem' => [
            'name' => 'Bemba',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ichibemba',
            'regional' => 'bem_ZM',
            'flag' => '🇿🇲',
        ],
        'bez' => [
            'name' => 'Bena',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Hibena',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'bg' => [
            'name' => 'Bulgarian',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Български',
            'regional' => 'bg_BG',
            'flag' => '🇧🇬',
        ],
        'bh' => [
            'name' => 'Bihari',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bihari',
            'regional' => '',
            'flag' => '🇮🇳',
        ],
        'bi' => [
            'name' => 'Bislama',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bislama',
            'regional' => '',
            'flag' => '🇻🇺',
        ],
        'bm' => [
            'name' => 'Bambara',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bamanakan',
            'regional' => '',
            'flag' => '🇲🇱',
        ],
        'bn' => [
            'name' => 'Bengali',
            'script' => 'Beng',
            'dir' => 'ltr',
            'native' => 'বাংলা',
            'regional' => 'bn_BD',
            'flag' => '🇧🇩',
        ],
        'bo' => [
            'name' => 'Tibetan',
            'script' => 'Tibt',
            'dir' => 'ltr',
            'native' => 'པོད་སྐད་',
            'regional' => 'bo_IN',
            'flag' => '🇨🇳',
        ],
        'br' => [
            'name' => 'Breton',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Brezhoneg',
            'regional' => 'br_FR',
            'flag' => '🇫🇷',
        ],
        'bra' => [
            'name' => 'Braj',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'ब्रज भाषा',
            'regional' => '',
            'flag' => '🇮🇳',
        ],
        'brx' => [
            'name' => 'Bodo',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'बड़ो',
            'regional' => 'brx_IN',
            'flag' => '🇮🇳',
        ],
        'bs' => [
            'name' => 'Bosnian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bosanski',
            'regional' => 'bs_BA',
            'flag' => '🇧🇦',
        ],
        'byn' => [
            'name' => 'Blin',
            'script' => 'Ethi',
            'dir' => 'ltr',
            'native' => 'ብሊን',
            'regional' => 'byn_ER',
            'flag' => '🇪🇷',
        ],

        // C
        //====================================================>
        'ca' => [
            'name' => 'Catalan',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Català',
            'regional' => 'ca_ES',
            'flag' => '🇦🇩',
        ],
        'ca-valencia' => [
            'name' => 'Valencian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Valencià',
            'regional' => '',
            'flag' => '🇪🇸',
        ],
        'cch' => [
            'name' => 'Atsam',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Atsam',
            'regional' => '',
            'flag' => '🇳🇬',
        ],
        'ce' => [
            'name' => 'Chechen',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Нохчийн мотт',
            'regional' => 'ce_RU',
            'flag' => '🇷🇺',
        ],
        'cgg' => [
            'name' => 'Chiga',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Rukiga',
            'regional' => '',
            'flag' => '🇺🇬',
        ],
        'ch' => [
            'name' => 'Chamorro',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Chamoru',
            'regional' => '',
            'flag' => '🇬🇺',
        ],
        'chr' => [
            'name' => 'Cherokee',
            'script' => 'Cher',
            'dir' => 'ltr',
            'native' => 'ᏣᎳᎩ',
            'regional' => '',
            'flag' => '🇺🇸',
        ],
        'co' => [
            'name' => 'Corsican',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Corsu',
            'regional' => '',
            'flag' => '🇫🇷',
        ],
        'cr' => [
            'name' => 'Cree',
            'script' => 'Cans',
            'dir' => 'ltr',
            'native' => 'ᓀᐦᐃᔭᐍᐏᐣ',
            'regional' => '',
            'flag' => '🇨🇦',
        ],
        'cs' => [
            'name' => 'Czech',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Čeština',
            'regional' => 'cs_CZ',
            'flag' => '🇨🇿',
        ],
        'cu' => [
            'name' => 'Church Slavic',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Ѩзыкъ словѣньскъ',
            'regional' => '',
            'flag' => '🇷🇸',
        ],
        'cv' => [
            'name' => 'Chuvash',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Чӑваш чӗлхи',
            'regional' => 'cv_RU',
            'flag' => '🇷🇺',
        ],
        'cy' => [
            'name' => 'Welsh',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Cymraeg',
            'regional' => 'cy_GB',
            'flag' => '🇬🇧',
        ],

        // D
        //====================================================>
        'da' => [
            'name' => 'Danish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Dansk',
            'regional' => 'da_DK',
            'flag' => '🇩🇰',
        ],
        'dav' => [
            'name' => 'Dawida',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kitaita',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'de' => [
            'name' => 'German',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Deutsch',
            'regional' => 'de_DE',
            'flag' => '🇩🇪',
        ],
        'de-AT' => [
            'name' => 'Austrian German',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Österreichisches Deutsch',
            'regional' => 'de_AT',
            'flag' => '🇦🇹',
        ],
        'de-CH' => [
            'name' => 'Swiss High German',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Schweizer Hochdeutsch',
            'regional' => 'de_CH',
            'flag' => '🇨🇭',
        ],
        'dje' => [
            'name' => 'Zarma',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Zarmaciine',
            'regional' => '',
            'flag' => '🇳🇪',
        ],
        'doi' => [
            'name' => 'Dogri',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'डोगरी',
            'regional' => 'doi_IN',
            'flag' => '🇮🇳',
        ],
        'dua' => [
            'name' => 'Duala',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Duálá',
            'regional' => '',
            'flag' => '🇨🇲',
        ],
        'dv' => [
            'name' => 'Divehi',
            'script' => 'Thaa',
            'dir' => 'rtl',
            'native' => 'ދިވެހިބަސް',
            'regional' => 'dv_MV',
            'flag' => '🇲🇻',
        ],
        'dyo' => [
            'name' => 'Jola-Fonyi',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Joola',
            'regional' => '',
            'flag' => '🇸🇳',
        ],
        'dz' => [
            'name' => 'Dzongkha',
            'script' => 'Tibt',
            'dir' => 'ltr',
            'native' => 'རྫོང་ཁ',
            'regional' => 'dz_BT',
            'flag' => '🇧🇹',
        ],

        // E
        //====================================================>
        'ebu' => [
            'name' => 'Kiembu',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kĩembu',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'ee' => [
            'name' => 'Ewe',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Eʋegbe',
            'regional' => '',
            'flag' => '🇬🇭',
        ],
        'en' => [
            'name' => 'English',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'English',
            'regional' => 'en_GB',
            'flag' => '🇬🇧',
        ],
        'en-AU' => [
            'name' => 'Australian English',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Australian English',
            'regional' => 'en_AU',
            'flag' => '🇦🇺',
        ],
        'en-GB' => [
            'name' => 'British English',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'British English',
            'regional' => 'en_GB',
            'flag' => '🇬🇧',
        ],
        'en-US' => [
            'name' => 'U.S. English',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'U.S. English',
            'regional' => 'en_US',
            'flag' => '🇺🇸',
        ],
        'el' => [
            'name' => 'Greek',
            'script' => 'Grek',
            'dir' => 'ltr',
            'native' => 'Ελληνικά',
            'regional' => 'el_GR',
            'flag' => '🇬🇷',
        ],
        'eo' => [
            'name' => 'Esperanto',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Esperanto',
            'regional' => '',
            'flag' => '🏳',
        ],
        'es' => [
            'name' => 'Spanish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Español',
            'regional' => 'es_ES',
            'flag' => '🇪🇸',
        ],
        'et' => [
            'name' => 'Estonian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Eesti',
            'regional' => 'et_EE',
            'flag' => '🇪🇪',
        ],
        'eu' => [
            'name' => 'Basque',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Euskara',
            'regional' => 'eu_ES',
            'flag' => '🇪🇸',
        ],
        'ewo' => [
            'name' => 'Ewondo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ewondo',
            'regional' => '',
            'flag' => '🇨🇲',
        ],

        // F
        //====================================================>
        'fa' => [
            'name' => 'Persian',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'فارسی',
            'regional' => 'fa_IR',
            'flag' => '🇮🇷',
        ],
        'ff' => [
            'name' => 'Fulah',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Pulaar',
            'regional' => 'ff_SN',
            'flag' => '🇸🇳',
        ],
        'fi' => [
            'name' => 'Finnish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Suomi',
            'regional' => 'fi_FI',
            'flag' => '🇫🇮',
        ],
        'fil' => [
            'name' => 'Filipino',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Filipino',
            'regional' => 'fil_PH',
            'flag' => '🇵🇭',
        ],
        'fj' => [
            'name' => 'Fijian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Vosa Vakaviti',
            'regional' => '',
            'flag' => '🇫🇯',
        ],
        'fo' => [
            'name' => 'Faroese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Føroyskt',
            'regional' => 'fo_FO',
            'flag' => '🇫🇴',
        ],
        'fr' => [
            'name' => 'French',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Français',
            'regional' => 'fr_FR',
            'flag' => '🇫🇷',
        ],
        'fr-CA' => [
            'name' => 'Canadian French',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Français canadien',
            'regional' => 'fr_CA',
            'flag' => '🇨🇦',
        ],
        'fur' => [
            'name' => 'Friulian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Furlan',
            'regional' => 'fur_IT',
            'flag' => '🇮🇹',
        ],
        'fy' => [
            'name' => 'Western Frisian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Frysk',
            'regional' => 'fy_DE',
            'flag' => '🇩🇪',
        ],

        // G
        //====================================================>
        'ga' => [
            'name' => 'Irish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Gaeilge',
            'regional' => 'ga_IE',
            'flag' => '🇮🇪',
        ],
        'gaa' => [
            'name' => 'Ga',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ga',
            'regional' => '',
            'flag' => '🇬🇭',
        ],
        'gd' => [
            'name' => 'Scottish Gaelic',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Gàidhlig',
            'regional' => 'gd_GB',
            'flag' => '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
        ],
        'gl' => [
            'name' => 'Galician',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Galego',
            'regional' => 'gl_ES',
            'flag' => '🇪🇸',
        ],
        'gn' => [
            'name' => 'Guaraní',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Avañe’ẽ',
            'regional' => '',
            'flag' => '🇵🇾',
        ],
        'gsw' => [
            'name' => 'Swiss German',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Schwiizertüütsch',
            'regional' => '',
            'flag' => '🇨🇭',
        ],
        'gu' => [
            'name' => 'Gujarati',
            'script' => 'Gujr',
            'dir' => 'ltr',
            'native' => 'ગુજરાતી',
            'regional' => 'gu_IN',
            'flag' => '🇮🇳',
        ],
        'guz' => [
            'name' => 'Ekegusii',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ekegusii',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'gv' => [
            'name' => 'Manx',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Gaelg',
            'regional' => 'gv_GB',
            'flag' => '🇮🇲',
        ],

        // H
        //====================================================>
        'ha' => [
            'name' => 'Hausa',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Hausa',
            'regional' => 'ha_NG',
            'flag' => '🇳🇬',
        ],
        'haw' => [
            'name' => 'Hawaiian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'ʻŌlelo Hawaiʻi',
            'regional' => '',
            'flag' => '🇺🇸',
        ],
        'he' => [
            'name' => 'Hebrew',
            'script' => 'Hebr',
            'dir' => 'rtl',
            'native' => 'עברית',
            'regional' => 'he_IL',
            'flag' => '🇮🇱',
        ],
        'hi' => [
            'name' => 'Hindi',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'हिन्दी',
            'regional' => 'hi_IN',
            'flag' => '🇮🇳',
        ],
        'ho' => [
            'name' => 'Hiri Motu',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Hiri Motu',
            'regional' => '',
            'flag' => '🇵🇬',
        ],
        'hr' => [
            'name' => 'Croatian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Hrvatski',
            'regional' => 'hr_HR',
            'flag' => '🇭🇷',
        ],
        'ht' => [
            'name' => 'Haitian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kreyòl ayisyen',
            'regional' => 'ht_HT',
            'flag' => '🇭🇹',
        ],
        'hu' => [
            'name' => 'Hungarian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Magyar',
            'regional' => 'hu_HU',
            'flag' => '🇭🇺',
        ],
        'hy' => [
            'name' => 'Armenian',
            'script' => 'Armn',
            'dir' => 'ltr',
            'native' => 'Հայերէն',
            'regional' => 'hy_AM',
            'flag' => '🇦🇲',
        ],
        'hz' => [
            'name' => 'Herero',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Otjiherero',
            'regional' => '',
            'flag' => '🇳🇦',
        ],

        // I
        //====================================================>
        'ia' => [
            'name' => 'Interlingua',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Interlingua',
            'regional' => 'ia_FR',
            'flag' => '🇫🇷',
        ],
        'id' => [
            'name' => 'Indonesian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bahasa Indonesia',
            'regional' => 'id_ID',
            'flag' => '🇮🇩',
        ],
        'ig' => [
            'name' => 'Igbo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Igbo',
            'regional' => 'ig_NG',
            'flag' => '🇳🇬',
        ],
        'ii' => [
            'name' => 'Sichuan Yi',
            'script' => 'Yiii',
            'dir' => 'ltr',
            'native' => 'ꆈꌠꉙ',
            'regional' => '',
            'flag' => '🇨🇳',
        ],
        'ik' => [
            'name' => 'Inupiaq',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Iñupiaq',
            'regional' => 'ik_CA',
            'flag' => '🇺🇸',
        ],
        'io' => [
            'name' => 'Ido',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ido',
            'regional' => '',
            'flag' => '🇮🇹',
        ],
        'is' => [
            'name' => 'Icelandic',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Íslenska',
            'regional' => 'is_IS',
            'flag' => '🇮🇸',
        ],
        'it' => [
            'name' => 'Italian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Italiano',
            'regional' => 'it_IT',
            'flag' => '🇮🇹',
        ],
        'iu' => [
            'name' => 'Inuktitut (Canadian Aboriginal Syllabics)',
            'script' => 'Cans',
            'dir' => 'ltr',
            'native' => 'ᐃᓄᒃᑎᑐᑦ',
            'regional' => 'iu_CA',
            'flag' => '🇨🇦',
        ],
        'iu-Latin' => [
            'name' => 'Inuktitut (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Inuktitut',
            'regional' => 'ia_FR',
            'flag' => '🇫🇷',
        ],

        // J
        //====================================================>
        'ja' => [
            'name' => 'Japanese',
            'script' => 'Jpan',
            'dir' => 'ltr',
            'native' => '日本語',
            'regional' => 'ja_JP',
            'flag' => '🇯🇵',
        ],
        'jmc' => [
            'name' => 'Machame',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kimachame',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'jv' => [
            'name' => 'Javanese (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Basa Jawa',
            'regional' => '',
            'flag' => '🇮🇩',
        ],
        'jv-Java' => [
            'name' => 'Javanese (Javanese)',
            'script' => 'Java',
            'dir' => 'ltr',
            'native' => 'ꦧꦱꦗꦮ',
            'regional' => '',
            'flag' => '🇮🇩',
        ],

        // K
        //====================================================>
        'ka' => [
            'name' => 'Georgian',
            'script' => 'Geor',
            'dir' => 'ltr',
            'native' => 'ქართული',
            'regional' => 'ka_GE',
            'flag' => '🇬🇪',
        ],
        'kab' => [
            'name' => 'Kabyle',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Taqbaylit',
            'regional' => 'kab_DZ',
            'flag' => '🇩🇿',
        ],
        'kaj' => [
            'name' => 'Jju',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kaje',
            'regional' => '',
            'flag' => '🇳🇬',
        ],
        'kam' => [
            'name' => 'Kamba',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kikamba',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'kcg' => [
            'name' => 'Tyap',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Katab',
            'regional' => '',
            'flag' => '🇳🇬',
        ],
        'kde' => [
            'name' => 'Makonde',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Chimakonde',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'kea' => [
            'name' => 'Kabuverdianu',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kabuverdianu',
            'regional' => '',
            'flag' => '🇨🇻',
        ],
        'kg' => [
            'name' => 'Kongo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kikongo',
            'regional' => '',
            'flag' => '🇨🇩',
        ],
        'khq' => [
            'name' => 'Koyra Chiini',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Koyra ciini',
            'regional' => '',
            'flag' => '🇲🇱',
        ],
        'ki' => [
            'name' => 'Kikuyu',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Gikuyu',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'kj' => [
            'name' => 'Kuanyama',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kwanyama',
            'regional' => '',
            'flag' => '🇳🇦',
        ],
        'kk' => [
            'name' => 'Kazakh',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Қазақ тілі',
            'regional' => 'kk_KZ',
            'flag' => '🇰🇿',
        ],
        'kl' => [
            'name' => 'Kalaallisut',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kalaallisut',
            'regional' => 'kl_GL',
            'flag' => '🇬🇱',
        ],
        'kln' => [
            'name' => 'Kalenjin',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kalenjin',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'km' => [
            'name' => 'Khmer',
            'script' => 'Khmr',
            'dir' => 'ltr',
            'native' => 'ភាសាខ្មែរ',
            'regional' => 'km_KH',
            'flag' => '🇰🇭',
        ],
        'kn' => [
            'name' => 'Kannada',
            'script' => 'Knda',
            'dir' => 'ltr',
            'native' => 'ಕನ್ನಡ',
            'regional' => 'kn_IN',
            'flag' => '🇮🇳',
        ],
        'ko' => [
            'name' => 'Korean',
            'script' => 'Hang',
            'dir' => 'ltr',
            'native' => '한국어',
            'regional' => 'ko_KR',
            'flag' => '🇰🇷',
        ],
        'kok' => [
            'name' => 'Konkani',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'कोंकणी',
            'regional' => 'kok_IN',
            'flag' => '🇮🇳',
        ],
        'kr' => [
            'name' => 'Kanuri',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kanuri',
            'regional' => '',
            'flag' => '🇳🇪',
        ],
        'ks' => [
            'name' => 'Kashmiri (Arabic)',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'کأشُر',
            'regional' => 'ks_IN',
            'flag' => '🇮🇳',
        ],
        'ks-Deva' => [
            'name' => 'Kashmiri (Devaganari)',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'कॉशुर',
            'regional' => 'ks_IN',
            'flag' => '🇮🇳',
        ],
        'ksb' => [
            'name' => 'Shambala',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kishambaa',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'ksf' => [
            'name' => 'Bafia',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Rikpa',
            'regional' => '',
            'flag' => '🇨🇲',
        ],
        'ksh' => [
            'name' => 'Kölsch',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kölsch',
            'regional' => '',
            'flag' => '🇩🇪',
        ],
        'ku' => [
            'name' => 'Kurdish',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'کوردی',
            'regional' => 'ku_TR',
            'flag' => '🇹🇷',
        ],
        'kv' => [
            'name' => 'Komi',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Коми кыв',
            'regional' => '',
            'flag' => '🇷🇺',
        ],
        'kw' => [
            'name' => 'Cornish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kernewek',
            'regional' => 'kw_GB',
            'flag' => '🇬🇧',
        ],
        'ky' => [
            'name' => 'Kyrgyz',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Кыргыз',
            'regional' => 'ky_KG',
            'flag' => '🇰🇬',
        ],

        // L
        //====================================================>
        'la' => [
            'name' => 'Latin',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Latine',
            'regional' => '',
            'flag' => '🏴',
        ],
        'lag' => [
            'name' => 'Langi',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kɨlaangi',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'lah' => [
            'name' => 'Lahnda',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Lahnda',
            'regional' => '',
            'flag' => '🇵🇰',
        ],
        'lb' => [
            'name' => 'Luxembourgish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Lëtzebuergesch',
            'regional' => 'lb_LU',
            'flag' => '',
        ],
        'lg' => [
            'name' => 'Ganda',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Luganda',
            'regional' => 'lg_UG',
            'flag' => '🇺🇬',
        ],
        'li' => [
            'name' => 'Limburgish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Limburgs',
            'regional' => 'li_BE',
            'flag' => '🇧🇪',
        ],
        'ln' => [
            'name' => 'Lingala',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Lingála',
            'regional' => '',
            'flag' => '🇨🇩',
        ],
        'lo' => [
            'name' => 'Lao',
            'script' => 'Laoo',
            'dir' => 'ltr',
            'native' => 'ລາວ',
            'regional' => 'lo_LA',
            'flag' => '🇱🇦',
        ],
        'lt' => [
            'name' => 'Lithuanian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Lietuvių',
            'regional' => 'lt_LT',
            'flag' => '🇱🇹',
        ],
        'lu' => [
            'name' => 'Luba-Katanga',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tshiluba',
            'regional' => '',
            'flag' => '🇨🇩',
        ],
        'luo' => [
            'name' => 'Luo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Dholuo',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'luy' => [
            'name' => 'Oluluyia',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Luluhia',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'lv' => [
            'name' => 'Latvian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Latviešu',
            'regional' => 'lv_LV',
            'flag' => '🇱🇻',
        ],

        // M
        //====================================================>
        'mai' => [
            'name' => 'Maithili',
            'script' => 'Tirh',
            'dir' => 'ltr',
            'native' => 'मैथिली',
            'regional' => 'mai_IN',
            'flag' => '🇮🇳',
        ],
        'mas' => [
            'name' => 'Masai',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ɔl-Maa',
            'regional' => '',
            'flag' => '🇹🇿',
        ],
        'mer' => [
            'name' => 'Kimîîru',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kĩmĩrũ',
            'regional' => '',
            'flag' => '🇰🇪',
        ],
        'mfe' => [
            'name' => 'Morisyen',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kreol morisien',
            'regional' => '',
            'flag' => '🇲🇺',
        ],
        'mg' => [
            'name' => 'Malagasy',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Malagasy',
            'regional' => 'mg_MG',
            'flag' => '🇲🇬',
        ],
        'mgh' => [
            'name' => 'Makhuwa-Meetto',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Makua',
            'regional' => '',
            'flag' => '🇲🇿',
        ],
        'mh' => [
            'name' => 'Marshallese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kajin M̧ajeļ',
            'regional' => 'mh_MH',
            'flag' => '🇲🇭',
        ],
        'mi' => [
            'name' => 'Māori',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Māori',
            'regional' => 'mi_NZ',
            'flag' => '🇳🇿',
        ],
        'mk' => [
            'name' => 'Macedonian',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Македонски',
            'regional' => 'mk_MK',
            'flag' => '🇲🇰',
        ],
        'ml' => [
            'name' => 'Malayalam',
            'script' => 'Mlym',
            'dir' => 'ltr',
            'native' => 'മലയാളം',
            'regional' => 'ml_IN',
            'flag' => '🇮🇳',
        ],
        'mn' => [
            'name' => 'Mongolian (Cyrillic)',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Монгол',
            'regional' => 'mn_MN',
            'flag' => '🇲🇳',
        ],
        'mn-Mong' => [
            'name' => 'Mongolian (Mongolian)',
            'script' => 'Mong',
            'dir' => 'rtl',
            'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ',
            'regional' => 'mn_MN',
            'flag' => '🇲🇳',
        ],
        'mni' => [
            'name' => 'Manipuri',
            'script' => 'Beng',
            'dir' => 'ltr',
            'native' => 'মৈতৈ',
            'regional' => 'mni_IN',
            'flag' => '🇮🇳',
        ],
        'mr' => [
            'name' => 'Marathi',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'मराठी',
            'regional' => 'mr_IN',
            'flag' => '🇮🇳',
        ],
        'ms' => [
            'name' => 'Malay',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bahasa Melayu',
            'regional' => 'ms_MY',
            'flag' => '🇲🇾',
        ],
        'mt' => [
            'name' => 'Maltese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Malti',
            'regional' => 'mt_MT',
            'flag' => '🇲🇹',
        ],
        'mtr' => [
            'name' => 'Mewari',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Mewari',
            'regional' => '',
            'flag' => '🇮🇳',
        ],
        'mua' => [
            'name' => 'Mundang',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Mundang',
            'regional' => '',
            'flag' => '🇨🇲',
        ],
        'my' => [
            'name' => 'Burmese',
            'script' => 'Mymr',
            'dir' => 'ltr',
            'native' => 'မြန်မာဘာသာ',
            'regional' => 'my_MM',
            'flag' => '🇲🇲',
        ],

        // N
        //====================================================>
        'na' => [
            'name' => 'Nauru',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ekakairũ Naoero',
            'regional' => '',
            'flag' => '🇳🇷',
        ],
        'naq' => [
            'name' => 'Nama',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Khoekhoegowab',
            'regional' => '',
            'flag' => '🇳🇦',
        ],
        'nb' => [
            'name' => 'Norwegian Bokmål',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Bokmål',
            'regional' => 'nb_NO',
            'flag' => '🇳🇴',
        ],
        'nd' => [
            'name' => 'North Ndebele',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'IsiNdebele',
            'regional' => '',
            'flag' => '🇿🇼',
        ],
        'nds' => [
            'name' => 'Low German',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Plattdüütsch',
            'regional' => 'nds_DE',
            'flag' => '🇩🇪',
        ],
        'ne' => [
            'name' => 'Nepali',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'नेपाली',
            'regional' => '',
            'flag' => '🇳🇵',
        ],
        'ng' => [
            'name' => 'Ndonga',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'OshiNdonga',
            'regional' => '',
            'flag' => '🇳🇦',
        ],
        'nl' => [
            'name' => 'Dutch',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Nederlands',
            'regional' => 'nl_NL',
            'flag' => '🇳🇱',
        ],
        'nmg' => [
            'name' => 'Kwasio',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ngumba',
            'regional' => '',
            'flag' => '🇨🇲',
        ],
        'nn' => [
            'name' => 'Norwegian Nynorsk',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Nynorsk',
            'regional' => 'nn_NO',
            'flag' => '🇳🇴',
        ],
        'nr' => [
            'name' => 'South Ndebele',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'IsiNdebele',
            'regional' => 'nr_ZA',
            'flag' => '🇿🇦',
        ],
        'nso' => [
            'name' => 'Northern Sotho',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Sesotho sa Leboa',
            'regional' => 'nso_ZA',
            'flag' => '🇿🇦',
        ],
        'nus' => [
            'name' => 'Nuer',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Thok Nath',
            'regional' => '',
            'flag' => '🇸🇸',
        ],
        'nv' => [
            'name' => 'Navajo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Diné bizaad',
            'regional' => '',
            'flag' => '🇺🇸',
        ],
        'ny' => [
            'name' => 'Chewa',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'ChiCheŵa',
            'regional' => '',
            'flag' => '🇲🇼',
        ],
        'nyn' => [
            'name' => 'Nyankole',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Runyankore',
            'regional' => '',
            'flag' => '🇺🇬',
        ],

        // O
        //====================================================>
        'oc' => [
            'name' => 'Occitan',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Occitan',
            'regional' => 'oc_FR',
            'flag' => '🇫🇷',
        ],
        'oj' => [
            'name' => 'Ojibwa',
            'script' => 'Cans',
            'dir' => 'ltr',
            'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ',
            'regional' => '',
            'flag' => '🇨🇦',
        ],
        'om' => [
            'name' => 'Oromo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Oromoo',
            'regional' => 'om_ET',
            'flag' => '🇪🇹',
        ],
        'or' => [
            'name' => 'Oriya',
            'script' => 'Orya',
            'dir' => 'ltr',
            'native' => 'ଓଡ଼ିଆ',
            'regional' => 'or_IN',
            'flag' => '🇮🇳',
        ],
        'os' => [
            'name' => 'Ossetic',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Ирон',
            'regional' => 'os_RU',
            'flag' => '🇷🇺',
        ],

        // P
        //====================================================>
        'pa' => [
            'name' => 'Punjabi (Gurmukhi)',
            'script' => 'Guru',
            'dir' => 'ltr',
            'native' => 'ਪੰਜਾਬੀ',
            'regional' => 'pa_IN',
            'flag' => '🇮🇳',
        ],
        'pa-Arab' => [
            'name' => 'Punjabi (Arabic)',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'پنجاب',
            'regional' => 'pa_IN',
            'flag' => '🇮🇳',
        ],
        'pi' => [
            'name' => 'Pahari-Potwari',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Pāli',
            'regional' => '',
            'flag' => '🏳',
        ],
        'pl' => [
            'name' => 'Polish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Polski',
            'regional' => 'pl_PL',
            'flag' => '🇵🇱',
        ],
        'pra' => [
            'name' => 'Prakrit',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'प्राकृत',
            'regional' => '',
            'flag' => '🏳',
        ],
        'ps' => [
            'name' => 'Pashto',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'پښتو',
            'regional' => 'ps_AF',
            'flag' => '🇦🇫',
        ],
        'pt' => [
            'name' => 'Portuguese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Português',
            'regional' => 'pt_PT',
            'flag' => '🇵🇹',
        ],
        'pt-BR' => [
            'name' => 'Brazilian Portuguese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Português do Brasil',
            'regional' => 'pt_BR',
            'flag' => '🇧🇷',
        ],

        // Q
        //====================================================>
        'qu' => [
            'name' => 'Quechua',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Runa Simi',
            'regional' => '',
            'flag' => '🏳',
        ],

        // R
        //====================================================>
        'raj' => [
            'name' => 'Rajasthani',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'राजस्थानी',
            'regional' => '',
            'flag' => '🏳',
        ],
        'ro' => [
            'name' => 'Romanian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Română',
            'regional' => 'ro_RO',
            'flag' => '🇷🇴',
        ],
        'rof' => [
            'name' => 'Rombo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kihorombo',
            'regional' => '',
            'flag' => '🏳',
        ],
        'rm' => [
            'name' => 'Romansh',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Rumantsch',
            'regional' => '',
            'flag' => '🏳',
        ],
        'rn' => [
            'name' => 'Rundi',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ikirundi',
            'regional' => '',
            'flag' => '🏳',
        ],
        'ru' => [
            'name' => 'Russian',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Русский',
            'regional' => 'ru_RU',
            'flag' => '🇷🇺',
        ],
        'rw' => [
            'name' => 'Kinyarwanda',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kinyarwanda',
            'regional' => 'rw_RW',
            'flag' => '🇷🇼',
        ],
        'rwk' => [
            'name' => 'Rwa',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kiruwa',
            'regional' => '',
            'flag' => '🏳',
        ],

        // S
        //====================================================>
        'sa' => [
            'name' => 'Sanskrit',
            'script' => 'Deva',
            'dir' => 'ltr',
            'native' => 'संस्कृतम्',
            'regional' => 'sa_IN',
            'flag' => '🇮🇳',
        ],
        'sah' => [
            'name' => 'Yakut',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Саха тыла',
            'regional' => '',
            'flag' => '🏳',
        ],
        'saq' => [
            'name' => 'Samburu',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kisampur',
            'regional' => '',
            'flag' => '🏳',
        ],
        'sbp' => [
            'name' => 'Sileibi',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Ishisangu',
            'regional' => '',
            'flag' => '🏳',
        ],
        'sc' => [
            'name' => 'Sardinian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Sardu',
            'regional' => 'sc_IT',
            'flag' => '🇮🇹',
        ],
        'sd' => [
            'name' => 'Sindhi',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'سنڌي',
            'regional' => 'sd_IN',
            'flag' => '🇮🇳',
        ],
        'se' => [
            'name' => 'Northern Sami',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Davvisámegiella',
            'regional' => 'se_NO',
            'flag' => '🇳🇴',
        ],
        'seh' => [
            'name' => 'Sena',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Sena',
            'regional' => '',
            'flag' => '🏳',
        ],
        'ses' => [
            'name' => 'Songhay',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Koyraboro senni',
            'regional' => '',
            'flag' => '🏳',
        ],
        'sg' => [
            'name' => 'Sango',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Sängö',
            'regional' => '',
            'flag' => '🏳',
        ],
        'sh' => [
            'name' => 'Serbo-Croatian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Srpskohrvatski',
            'regional' => '',
            'flag' => '🏳',
        ],
        'shi' => [
            'name' => 'Tachelhit (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tashelhit',
            'regional' => '',
            'flag' => '🏳',
        ],
        'shi-Tfng' => [
            'name' => 'Tachelhit (Tifinagh)',
            'script' => 'Tfng',
            'dir' => 'rtl',
            'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ',
            'regional' => '',
            'flag' => '🏳',
        ],
        'si' => [
            'name' => 'Sinhala',
            'script' => 'Sinh',
            'dir' => 'ltr',
            'native' => 'සිංහල',
            'regional' => 'si_LK',
            'flag' => '🇱🇰',
        ],
        'sid' => [
            'name' => 'Sidamo',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Sidaamu Afo',
            'regional' => 'sid_ET',
            'flag' => '🇪🇹',
        ],
        'sk' => [
            'name' => 'Slovak',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Slovenčina',
            'regional' => 'sk_SK',
            'flag' => '🇸🇰',
        ],
        'sl' => [
            'name' => 'Slovene',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Slovenščina',
            'regional' => 'sl_SI',
            'flag' => '🇸🇮',
        ],
        'sm' => [
            'name' => 'Samoan',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Gagana fa’a Sāmoa',
            'regional' => '',
            'flag' => '🏳',
        ],
        'sn' => [
            'name' => 'Shona',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'ChiShona',
            'regional' => '',
            'flag' => '🏳',
        ],
        'so' => [
            'name' => 'Somali',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Soomaali',
            'regional' => 'so_SO',
            'flag' => '🇸🇴',
        ],
        'sq' => [
            'name' => 'Albanian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Shqip',
            'regional' => 'sq_AL',
            'flag' => '🇦🇱',
        ],
        'sr' => [
            'name' => 'Serbian (Cyrillic)',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Српски',
            'regional' => 'sr_RS',
            'flag' => '🇷🇸',
        ],
        'sr-Latin' => [
            'name' => 'Serbian (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Srpski',
            'regional' => 'sr_RS',
            'flag' => '🇷🇸',
        ],
        'ss' => [
            'name' => 'Swati',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Siswati',
            'regional' => 'ss_ZA',
            'flag' => '🇸🇿',
        ],
        'ssy' => [
            'name' => 'Saho',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Saho',
            'regional' => '',
            'flag' => '🏳',
        ],
        'st' => [
            'name' => 'Southern Sotho',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Sesotho',
            'regional' => 'st_ZA',
            'flag' => '🇿🇦',
        ],
        'su' => [
            'name' => 'Sundanese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Basa Sunda',
            'regional' => '',
            'flag' => '🏳',
        ],
        'sv' => [
            'name' => 'Swedish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Svenska',
            'regional' => 'sv_SE',
            'flag' => '🇸🇪',
        ],
        'sw' => [
            'name' => 'Swahili',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kiswahili',
            'regional' => 'sw_KE',
            'flag' => '🇰🇪',
        ],
        'swc' => [
            'name' => 'Congo Swahili',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kiswahili ya Kongo',
            'regional' => '',
            'flag' => '🏳',
        ],

        // T
        //====================================================>
        'ta' => [
            'name' => 'Tamil',
            'script' => 'Taml',
            'dir' => 'ltr',
            'native' => 'தமிழ்',
            'regional' => 'ta_IN',
            'flag' => '🇮🇳',
        ],
        'te' => [
            'name' => 'Telugu',
            'script' => 'Telu',
            'dir' => 'ltr',
            'native' => 'తెలుగు',
            'regional' => 'te_IN',
            'flag' => '🇮🇳',
        ],
        'teo' => [
            'name' => 'Teso',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Kiteso',
            'regional' => '',
            'flag' => '🏳',
        ],
        'tg' => [
            'name' => 'Tajik (Cyrillic)',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Тоҷикӣ',
            'regional' => 'tg_TJ',
            'flag' => '🇹🇯',
        ],
        'tg-Arab' => [
            'name' => 'Tajik (Arabic)',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'تاجیکی',
            'regional' => 'tg_TJ',
            'flag' => '🇹🇯',
        ],
        'tg-Latin' => [
            'name' => 'Tajik (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tojikī',
            'regional' => 'tg_TJ',
            'flag' => '🇹🇯',
        ],
        'th' => [
            'name' => 'Thai',
            'script' => 'Thai',
            'dir' => 'ltr',
            'native' => 'ไทย',
            'regional' => 'th_TH',
            'flag' => '🇹🇭',
        ],
        'ti' => [
            'name' => 'Tigrinya',
            'script' => 'Ethi',
            'dir' => 'ltr',
            'native' => 'ትግርኛ',
            'regional' => 'ti_ET',
            'flag' => '🇪🇹',
        ],
        'tig' => [
            'name' => 'Tigre',
            'script' => 'Ethi',
            'dir' => 'ltr',
            'native' => 'ትግረ',
            'regional' => 'tig_ER',
            'flag' => '🇪🇷',
        ],
        'tk' => [
            'name' => 'Turkmen',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Түркменче',
            'regional' => 'tk_TM',
            'flag' => '🇹🇲',
        ],
        'tl' => [
            'name' => 'Tagalog',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tagalog',
            'regional' => 'tl_PH',
            'flag' => '🇵🇭',
        ],
        'tn' => [
            'name' => 'Tswana',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Setswana',
            'regional' => 'tn_ZA',
            'flag' => '🇿🇦',
        ],
        'to' => [
            'name' => 'Tongan',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Lea fakatonga',
            'regional' => '',
            'flag' => '🏳',
        ],
        'tr' => [
            'name' => 'Turkish',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Türkçe',
            'regional' => 'tr_TR',
            'flag' => '🇹🇷',
        ],
        'trv' => [
            'name' => 'Taroko',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Seediq',
            'regional' => '',
            'flag' => '🏳',
        ],
        'ts' => [
            'name' => 'Tsonga',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Xitsonga',
            'regional' => 'ts_ZA',
            'flag' => '🇿🇦',
        ],
        'tt' => [
            'name' => 'Tatar',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Татар теле',
            'regional' => 'tt_RU',
            'flag' => '🇷🇺',
        ],
        'tw' => [
            'name' => 'Twi',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Twi',
            'regional' => '',
            'flag' => '🏳',
        ],
        'twq' => [
            'name' => 'Tasawaq',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tasawaq senni',
            'regional' => '',
            'flag' => '🏳',
        ],
        'ty' => [
            'name' => 'Tahitian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Reo Māohi',
            'regional' => '',
            'flag' => '🏳',
        ],
        'tzm' => [
            'name' => 'Central Atlas Tamazight (Tifinagh)',
            'script' => 'Tfng',
            'dir' => 'rtl',
            'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ',
            'regional' => '',
            'flag' => '🏳',
        ],
        'tzm-Latin' => [
            'name' => 'Central Atlas Tamazight (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tamazight',
            'regional' => '',
            'flag' => '🏳',
        ],

        // U
        //====================================================>
        'ug' => [
            'name' => 'Uyghur',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'ئۇيغۇرچە',
            'regional' => 'ug_CN',
            'flag' => '🇨🇳',
        ],
        'uk' => [
            'name' => 'Ukrainian',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Українська',
            'regional' => 'uk_UA',
            'flag' => '🇺🇦',
        ],
        'ur' => [
            'name' => 'Urdu',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'اردو',
            'regional' => 'ur_PK',
            'flag' => '🇵🇰',
        ],
        'uz' => [
            'name' => 'Uzbek (Cyrillic)',
            'script' => 'Cyrl',
            'dir' => 'ltr',
            'native' => 'Ўзбек',
            'regional' => 'uz_UZ',
            'flag' => '🇺🇿',
        ],
        'uz-Arab' => [
            'name' => 'Uzbek (Arabic)',
            'script' => 'Arab',
            'dir' => 'rtl',
            'native' => 'اۉزبېک',
            'regional' => '',
            'flag' => '🏳',
        ],
        'uz-Latin' => [
            'name' => 'Uzbek (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Oʼzbekcha',
            'regional' => 'uz_UZ',
            'flag' => '🇺🇿',
        ],

        // V
        //====================================================>
        'vai' => [
            'name' => 'Vai (Vai)',
            'script' => 'Vaii',
            'dir' => 'ltr',
            'native' => 'ꕙꔤ',
            'regional' => '',
            'flag' => '🏳',
        ],
        'vai-Latin' => [
            'name' => 'Vai (Latin)',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Viyamíĩ',
            'regional' => '',
            'flag' => '🏳',
        ],
        've' => [
            'name' => 'Venda',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tshivenḓa',
            'regional' => 've_ZA',
            'flag' => '🇿🇦',
        ],
        'vi' => [
            'name' => 'Vietnamese',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Tiếng Việt',
            'regional' => 'vi_VN',
            'flag' => '🇻🇳',
        ],
        'vo' => [
            'name' => 'Volapük',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Volapük',
            'regional' => '',
            'flag' => '🏳',
        ],

        // W
        //====================================================>
        'wa' => [
            'name' => 'Walloon',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Walon',
            'regional' => 'wa_BE',
            'flag' => '🇧🇪',
        ],
        'wae' => [
            'name' => 'Walser',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Walser',
            'regional' => 'wae_CH',
            'flag' => '🇨🇭',
        ],
        'wal' => [
            'name' => 'Wolaytta',
            'script' => 'Ethi',
            'dir' => 'ltr',
            'native' => 'ወላይታቱ',
            'regional' => 'wal_ET',
            'flag' => '🇪🇹',
        ],
        'wen' => [
            'name' => 'Sorbian',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Wendic',
            'regional' => '',
            'flag' => '🏳',
        ],
        'wo' => [
            'name' => 'Wolof',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Wolof',
            'regional' => 'wo_SN',
            'flag' => '🇸🇳',
        ],

        // X
        //====================================================>
        'xh' => [
            'name' => 'Xhosa',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'IsiXhosa',
            'regional' => 'xh_ZA',
            'flag' => '🇿🇦',
        ],
        'xog' => [
            'name' => 'Soga',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Olusoga',
            'regional' => '',
            'flag' => '🏳',
        ],

        // Y
        //====================================================>
        'yav' => [
            'name' => 'Yangben',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Nuasue',
            'regional' => '',
            'flag' => '🏳',
        ],
        'yi' => [
            'name' => 'Yiddish',
            'script' => 'Hebr',
            'dir' => 'rtl',
            'native' => 'ייִדיש',
            'regional' => 'yi_US',
            'flag' => '🇺🇸',
        ],
        'yo' => [
            'name' => 'Yoruba',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'Èdè Yorùbá',
            'regional' => 'yo_NG',
            'flag' => '🇳🇬',
        ],
        'yue' => [
            'name' => 'Yue',
            'script' => 'Hant',
            'dir' => 'ltr',
            'native' => '廣州話',
            'regional' => 'yue_HK',
            'flag' => '🇭🇰',
        ],

        // Z
        //====================================================>
        'zh' => [
            'name' => 'Chinese (Simplified)',
            'script' => 'Hans',
            'dir' => 'ltr',
            'native' => '简体中文',
            'regional' => 'zh_CN',
            'flag' => '🇨🇳',
        ],
        'zh-Hant' => [
            'name' => 'Chinese (Traditional)',
            'script' => 'Hant',
            'dir' => 'ltr',
            'native' => '繁體中文',
            'regional' => 'zh_CN',
            'flag' => '🇨🇳',
        ],
        'zu' => [
            'name' => 'Zulu',
            'script' => 'Latn',
            'dir' => 'ltr',
            'native' => 'IsiZulu',
            'regional' => 'zu_ZA',
            'flag' => '🇿🇦',
        ],
    ],
];
